[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  node_version = "18"

[build.environment]
  NODE_VERSION = "18.12.0"
  NODE_ENV = "production"
